INSERT INTO `department_updates` (`area`,`title`,`detail`,`metric`,`status`,`responsible`,`report_date`,`submitted_by`)
VALUES
('Comercial','IASA · fondo de USD 30.000 resuelto','La alerta se mantiene en el historial como resuelta. Fuente: Informe Ejecutivo Comité MCB 360, corte 02-sep-2026.','USD 30.000','Completado','Carolina Herrera','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Comercial','QUIMPAC, INTEROC y AGRIPAC sin responsable','Los tres asuntos continúan sin responsable asignado. Fuente: Informe Ejecutivo Comité MCB 360, corte 02-sep-2026.','3 clientes','Requiere decisión CEO','Carolina Herrera','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Comercial','GISIS · estado contradictorio','Carolina reporta la licitación en pausa y Vanessa trabajo activo. No se adopta ninguna versión como definitiva hasta conciliación. Fuente: Informe Ejecutivo Comité MCB 360, corte 02-sep-2026.','','Por conciliar','Carolina Herrera / Vanessa Naranjo','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Regulatorio','Corte regulatorio del 2 de septiembre','Acumulado USD 7.850; USD 4.790 facturados el día 1; USD 1.100 creados sin facturar; 5 licencias. La lista completa de prospectos no consta y debe restituirse. Fuente: Informe Ejecutivo Comité MCB 360, corte 02-sep-2026.','USD 7.850 acumulado','En seguimiento','Lilibeth Terranova','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Facturación','Correcciones de cálculo y auditabilidad','Corregir meta diaria con DAI USD 310.000 / 30 días y hacer que Total cuadre con Subtotal + IVA. Fuente: revisión cruzada de Francisco Jaramillo, 02-sep-2026.','','En riesgo','Rebeca Sánchez','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Auditoría y Control','Hallazgos de revisión cruzada','Cuantificar cuellos de botella de Despacho; escalar usuario ECUASIGAD; conciliar GISIS; corregir plantillas y formatos. Fuente: revisión cruzada de Francisco Jaramillo, 02-sep-2026.','5 hallazgos principales','En seguimiento','Francisco Jaramillo','2026-09-02','k2v5nc8k7s@privaterelay.appleid.com'),
('Despacho','Seguimiento de cumplimiento de Despacho','Se mantiene presión por indicadores de trámite anticipado; se gestiona la facturación de 45 trámites; continúa el seguimiento a Grupo Wong; se informó otra hoja de cambio. La explicación sobre manuales e infraestructura corresponde a sistemas de Aduana/ECUAPASS y queda pendiente de respaldo o confirmación directa de Aduana. Fuente: comentario de María Fernanda Manrique recibido por Mario Coka el 03-sep-2026.','45 trámites pendientes','En seguimiento','María Fernanda Manrique','2026-09-03','k2v5nc8k7s@privaterelay.appleid.com');
