ALTER TABLE `grupo_une_operations` ADD `notice_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `oc_creation_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `value_quantity_sent_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `oc_balanced_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `oc_retention_notice_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `oc_release_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `approval_1_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `approval_2_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `approval_3_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `cxp_sent_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `cxp_registered_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `warehouse_entry_requested_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `storage_cost_cents` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `weight_kg` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `values_requested_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `arrival_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `macobsa_payment_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `transport_mode` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `documents_received_at` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `grupo_une_operations` ADD `documents_sent_executive_at` text DEFAULT '' NOT NULL;